_GCP_PROJECT_ID: "academia-2024-1"
_BIGQUERY_DATASET_ID: "your_name_in_lowercase_titanic"
_BIGQUERY_FACTS_TABLE_ID: "titanic_facts"
_BIGQUERY_STAGING_TABLE_ID: "titanic_raw"
_TOPIC_UPDATE_FACTS_COMPLETE: "joana-update-facts-complete"
